# Generated by Django 5.0.4 on 2024-06-03 10:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True)),
                ('title', models.CharField()),
                ('price_usd', models.PositiveIntegerField()),
                ('odometer', models.PositiveIntegerField()),
                ('username', models.CharField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='UA')),
                ('image_url', models.JSONField(blank=True, null=True)),
                ('images_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('car_number', models.CharField(blank=True, null=True)),
                ('car_vin', models.CharField(blank=True, null=True)),
                ('datetime_found', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
